[CmdletBinding()]
param(
    [string]$VaultRoot = '__VAULT_ROOT__',
    [switch]$Quiet
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-NoteTitle {
    param([string]$Path)
    $firstHeading = Get-Content -LiteralPath $Path | Where-Object { $_ -match '^# ' } | Select-Object -First 1
    if ($firstHeading) {
        return ($firstHeading -replace '^#\s+', '').Trim()
    }
    return [System.IO.Path]::GetFileNameWithoutExtension($Path)
}

function Get-RelativePath {
    param([string]$BasePath,[string]$ChildPath)
    $baseUri = [System.Uri]((Resolve-Path -LiteralPath $BasePath).Path + [System.IO.Path]::DirectorySeparatorChar)
    $childUri = [System.Uri](Resolve-Path -LiteralPath $ChildPath).Path
    return [System.Uri]::UnescapeDataString($baseUri.MakeRelativeUri($childUri).ToString()).Replace('\', '/')
}

$systemRoot = Join-Path $VaultRoot '00_System'
New-Item -ItemType Directory -Force -Path $systemRoot | Out-Null

$sections = @(
    @{ Name = 'Projects'; Folder = '20_Projects'; Output = 'Project Index.md'; Intro = 'Generated index of curated project notes.' },
    @{ Name = 'Knowledge'; Folder = '30_Knowledge'; Output = 'Knowledge Index.md'; Intro = 'Generated index of reusable knowledge notes.' },
    @{ Name = 'Decisions'; Folder = '40_Decisions'; Output = 'Decision Index.md'; Intro = 'Generated index of decision records.' },
    @{ Name = 'Prompts'; Folder = '50_Prompts'; Output = 'Prompt Index.md'; Intro = 'Generated index of reusable prompt notes.' },
    @{ Name = 'References'; Folder = '60_References'; Output = 'Reference Index.md'; Intro = 'Generated index of durable reference notes.' }
)

foreach ($section in $sections) {
    $folderPath = Join-Path $VaultRoot $section.Folder
    $outputPath = Join-Path $systemRoot $section.Output
    $lines = @(
        "# $($section.Name) Index",
        '',
        $section.Intro,
        '',
        '_This file is generated by `Compile-VaultKnowledge.ps1`._',
        ''
    )

    if (Test-Path -LiteralPath $folderPath) {
        $notes = Get-ChildItem -LiteralPath $folderPath -Recurse -Filter '*.md' -File | Where-Object { $_.Name -ne 'README.md' -and $_.Name -ne 'AGENTS.override.md' } | Sort-Object FullName
        foreach ($note in $notes) {
            $title = Get-NoteTitle -Path $note.FullName
            $relative = Get-RelativePath -BasePath $VaultRoot -ChildPath $note.FullName
            $lines += "- [$title](../$relative)"
        }
    }

    Set-Content -LiteralPath $outputPath -Value ($lines -join [Environment]::NewLine)
}

$draftRoot = Join-Path $VaultRoot '10_Inbox\Agent Drafts'
$draftDigestPath = Join-Path $systemRoot 'Draft Digest.md'
$draftDigestLines = @(
    '# Draft Digest',
    '',
    'Generated summary of current draft notes waiting for curation.',
    '',
    '_This file is generated by `Compile-VaultKnowledge.ps1`._',
    ''
)

if (Test-Path -LiteralPath $draftRoot) {
    $drafts = Get-ChildItem -LiteralPath $draftRoot -Filter '*.md' -File | Sort-Object LastWriteTime -Descending
    foreach ($draft in $drafts) {
        $title = Get-NoteTitle -Path $draft.FullName
        $relative = Get-RelativePath -BasePath $VaultRoot -ChildPath $draft.FullName
        $draftDigestLines += "- [$title](../$relative)"
    }
}

Set-Content -LiteralPath $draftDigestPath -Value ($draftDigestLines -join [Environment]::NewLine)

$homePath = Join-Path $VaultRoot '00 Home.md'
if (Test-Path -LiteralPath $homePath) {
    $homeContent = Get-Content -LiteralPath $homePath -Raw
    $compiledViewsBlock = @(
        '<!-- ROOTED_AGENTS_COMPILED_VIEWS_START -->',
        '## Compiled Views',
        '',
        '- [[Project Index]]',
        '- [[Knowledge Index]]',
        '- [[Decision Index]]',
        '- [[Prompt Index]]',
        '- [[Reference Index]]',
        '- [[Draft Digest]]',
        '<!-- ROOTED_AGENTS_COMPILED_VIEWS_END -->'
    ) -join [Environment]::NewLine

    if ($homeContent -match '(?s)<!-- ROOTED_AGENTS_COMPILED_VIEWS_START -->.*?<!-- ROOTED_AGENTS_COMPILED_VIEWS_END -->') {
        $updatedHomeContent = [regex]::Replace($homeContent, '(?s)<!-- ROOTED_AGENTS_COMPILED_VIEWS_START -->.*?<!-- ROOTED_AGENTS_COMPILED_VIEWS_END -->', $compiledViewsBlock)
        Set-Content -LiteralPath $homePath -Value $updatedHomeContent
    }
    elseif ($homeContent -match '(?ms)^## Compiled Views\b.*?(?=(\r?\n##\s)|\z)') {
        $updatedHomeContent = [regex]::Replace($homeContent, '(?ms)^## Compiled Views\b.*?(?=(\r?\n##\s)|\z)', $compiledViewsBlock)
        Set-Content -LiteralPath $homePath -Value $updatedHomeContent
    }
    else {
        $append = @(
            '',
            $compiledViewsBlock
        ) -join [Environment]::NewLine
        Set-Content -LiteralPath $homePath -Value ($homeContent + $append)
    }
}

if (-not $Quiet) {
    Write-Host "Compiled vault knowledge under: $systemRoot"
}
